### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by ajlee2006** [JosherLo/Maze#5]
I receive the following error when trying to run Main:
`Error: JavaFX runtime components are missing, and are required to run this application`

**Comment by ajlee2006** [comment]
To fix this, I made a new class fakeMain, containing:
```
package sample;

public class fakeMain {
    public static void main(String[] args) {
        Main.main(null);
    }
}

**Comment by JosherLo** [comment]
Issue caused because I used VM options instead of module-info.java.

module-info.java added
